model:
  path: "models/die_crack_classifier.onnx"
  image_size: 224
  classes: ["cracked die at upper left part", "cracked die at lower left part", "cracked die at lower right part", "cracked die at upper right part", "shattered die"]

documents:
  static_path: "documents/"
  upload_path: "uploads/"
  chunk_size: 1000
  chunk_overlap: 55

rag:
  collection_name: "MOSFET_Die_Crack_Analysis"
  retrieval_k: 10
  confidence_threshold: 0.2